[package]
name = "gameyfin-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Client for the Gameyfin server API (Hilla RPC + REST)"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
url.workspace = true
tokio.workspace = true
tracing.workspace = true
time.workspace = true
async-trait = "0.1"
regex = "1"
futures-util = "0.3"

[dev-dependencies]
mockito = "1"
tokio = { version = "1", features = ["full"] }
