// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationCategory } from "./NotificationCategory";

/**
 * One entry in the in-app list.
 */
export type AppNotification = { id: number, category: NotificationCategory, title: string, body: string, createdAt: string, 
/**
 * The page that deals with it, opened when it is clicked.
 */
route: string | null, read: boolean, };
