// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stick position, for continuous scrolling.
 */
export type AxisEvent = { rightX: number, rightY: number, };
