// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Button } from "./Button";

/**
 * One button going down, sent to the webview.
 */
export type ButtonEvent = { button: Button, 
/**
 * True when this is an auto-repeat rather than a fresh press, so the frontend can
 * choose to ignore repeats where they make no sense, such as activating a button.
 */
repeat: boolean, };
