// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A logical button, named for what the frontend binds rather than for a device.
 */
export type Button = "south" | "east" | "west" | "north" | "left-bumper" | "right-bumper" | "left-trigger" | "right-trigger" | "select" | "start" | "up" | "down" | "left" | "right";
