// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Component } from "./Component";

export type ComponentRelease = { component: Component, version: string, asset: string, url: string, sizeBytes: number, 
/**
 * From GitHub's own asset digest. `None` when it is absent, which is reported
 * rather than silently accepted.
 */
sha256: string | null, };
