// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionStatus = { configured: boolean, authenticated: boolean, 
/**
 * The server did not answer; the session is kept and the cached library shown.
 */
offline: boolean, serverUrl: string | null, username: string | null, };
