// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a controller is attached at all.
 */
export type ConnectionEvent = { connected: boolean, 
/**
 * The pad's name, for showing which one is in use.
 */
name: string | null, };
