// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginKind } from "./LoginKind";

export type ConnectionStatus = { configured: boolean, authenticated: boolean, 
/**
 * The server did not answer; the session is kept and the cached library shown.
 */
offline: boolean, serverUrl: string | null, username: string | null, 
/**
 * None when nothing is stored to sign in with.
 */
login: LoginKind | null, };
