// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `DownloadProviderDto`. Providers are contributed by plugins (`directdownload`,
 * `torrentdownload`); higher `priority` wins when several can serve a game.
 */
export type DownloadProvider = { key: string, name: string, priority: number, description: string, shortDescription: string | null, };
