// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchToggles } from "./LaunchToggles";

/**
 * A partial update of a game's own options; a field not sent is left alone.
 */
export type GameOptionsPatch = { launchArguments?: string, installerArguments?: string, launchEnvironment?: string, 
/**
 * `"auto"` or empty clears the override.
 */
runtimeOverride?: string, 
/**
 * Empty clears the pin.
 */
protonBuild?: string, launchToggles?: LaunchToggles, };
