// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameMetadata } from "./GameMetadata";
import type { Image } from "./Image";

/**
 * A `GameDto` (the `GameUserDto` variant).
 */
export type Game = { id: number, title: string, libraryId: number, summary: string | null, comment: string | null, 
/**
 * ISO-8601 date as serialized by Hilla from a Kotlin `LocalDate`.
 */
release: string | null, userRating: number | null, criticRating: number | null, platforms: Array<string>, genres: Array<string>, themes: Array<string>, publishers: Array<string>, developers: Array<string>, features: Array<string>, keywords: Array<string>, perspectives: Array<string>, collectionIds: Array<number>, cover: Image | null, header: Image | null, images: Array<Image>, videoUrls: Array<string>, metadata: GameMetadata, };
