// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledProton } from "./InstalledProton";
import type { LaunchToggles } from "./LaunchToggles";

export type GameOptions = { launchArguments: string, installerArguments: string, launchEnvironment: string, protonBuild: string | null, protonBuilds: Array<InstalledProton>, launchToggles: LaunchToggles, 
/**
 * Winetricks verbs the last failed start pointed at.
 */
suggestedWinetricks: Array<string>, };
