// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledProton } from "./InstalledProton";
import type { RuntimeChoice } from "./RuntimeChoice";

export type GameOptions = { launchArguments: string, installerArguments: string, launchEnvironment: string, runtimeOverride: string | null, 
/**
 * Only runtimes this machine has, so the picker cannot name one that fails at launch.
 */
availableRuntimes: Array<RuntimeChoice>, protonBuild: string | null, protonBuilds: Array<InstalledProton>, };
