// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledBusy } from "./InstalledBusy";
import type { Stage } from "./Stage";
import type { TransferProgress } from "./TransferProgress";

/**
 * What the UI renders for a game.
 */
export type GameState = { "kind": "not-installed" } | { "kind": "downloading", receivedBytes: number, totalBytes: number, bytesPerSecond: number, } | { "kind": "downloaded", archivePath: string, bytes: number, } | { "kind": "extracting", percent: number, } | { "kind": "extracted", path: string, setupCandidates: Array<string>, archivePresent: boolean, } | { "kind": "installing", progress?: TransferProgress, step?: string, } | { "kind": "preparing", message: string, progress?: TransferProgress, } | { "kind": "installed", path: string, executable: string | null, setupCandidates: Array<string>, stagingSetups: Array<string>, stagingPresent: boolean, busy: InstalledBusy | null, } | { "kind": "running", since: string, executable: string | null, runtime: string | null, } | { "kind": "failed", message: string, stage: Stage, 
/**
 * Kept so a failed launch still offers Play and the executable picker.
 */
path: string | null, executable: string | null, 
/**
 * The retry that helps is "as administrator", not a plain retry.
 */
elevationRequired: boolean, };
