// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `GameMetadataUserDto`. `original_ids` holds the Steam AppID for exact save matching; a
 * stock 2.4.0 server omits it, so matching falls back to the title.
 */
export type GameMetadata = { fileSize: number, originalIds: { [key in string]: string } | null, };
