// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentRelease } from "./ComponentRelease";
import type { InstalledGraphics } from "./InstalledGraphics";
import type { VulkanSupport } from "./VulkanSupport";

export type GraphicsStatus = { installed: InstalledGraphics, vulkan: VulkanSupport, vulkanLabel: string, latestDxvk: ComponentRelease | null, latestVkd3d: ComponentRelease | null, 
/**
 * What this driver should run, which is not always the newest release.
 */
recommendedDxvk: string | null, recommendedVkd3d: string | null, enabled: boolean, };
