// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Upstream's floors: DXVK 3.x needs Vulkan 1.4, 2.x needs 1.3, older hardware the 1.10.3
 * branch. vkd3d-proton needs 1.3 whatever DXVK is used.
 */
export type GraphicsTier = "current" | "vulkan13" | "legacy" | "unsupported";
