// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An `ImageDto`. `blurhash` lets the UI paint a placeholder before the bytes arrive.
 */
export type Image = { id: number, type: string, blurhash: string | null, };
