// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtonFamily } from "./ProtonFamily";

/**
 * A build on disk, ready to hand to umu as `PROTONPATH`.
 */
export type InstalledProton = { 
/**
 * The directory name, which is also how a game pins a build.
 */
name: string, family: ProtonFamily | null, 
/**
 * The build directory, holding the `proton` script.
 */
path: string, };
