// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferProgress } from "./TransferProgress";

/**
 * Work on an installed game, shown on its installed row rather than moving it to Downloads.
 */
export type InstalledBusy = { "kind": "preparing", message: string, progress?: TransferProgress, } | { "kind": "installing", progress?: TransferProgress, step?: string, } | { "kind": "failed", message: string, };
