// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledComponent } from "./InstalledComponent";

export type InstalledGraphics = { dxvk: InstalledComponent | null, vkd3d: InstalledComponent | null, };
