// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallOption = { key: string, label: string, description: string, 
/**
 * Hands control to a setup wizard, which asks where to install.
 */
interactive: boolean, 
/**
 * Why the option cannot be used yet.
 */
blockedBy: string | null, };
