// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Component } from "./Component";

export type InstalledComponent = { component: Component, version: string, 
/**
 * The directory holding `x64` and its 32-bit sibling.
 */
root: string, };
