// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Work on an installed game, shown on its installed row rather than moving it to Downloads.
 */
export type InstalledBusy = { "kind": "preparing", message: string, } | { "kind": "installing" } | { "kind": "failed", message: string, };
