// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallOption } from "./InstallOption";

export type InstallPlan = { payload: string, options: Array<InstallOption>, defaultInstallDir: string, 
/**
 * The path to paste into a setup wizard; `None` on Windows or when nothing will ask.
 */
windowsInstallPath: string | null, needsInstallPath: boolean, setupCandidates: Array<string>, 
/**
 * Where a file picker should start: the unpacked files, else the download folder.
 */
browseDir: string | null, };
