// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stored as `"auto"`, `"off"` or a number of MiB.
 */
export type InstallerMemoryLimit = "auto" | "off" | number;
