// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WineVariant } from "./WineVariant";

export type InstalledWine = { version: string, variant: WineVariant, binary: string, };
