// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proton features a game can opt into, offered as switches rather than typed variables.
 */
export type LaunchToggles = { 
/**
 * Wine's Wayland driver instead of XWayland.
 */
wayland: boolean, 
/**
 * 32-bit games through WOW64, so no 32-bit system libraries are needed.
 */
wow64: boolean, };
