// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryRoot = { path: string, isDefault: boolean, freeBytes: number | null, exists: boolean, };
