// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { GameState } from "./GameState";

export type LibraryEntry = { game: Game, state: GameState, minutesPlayed: number, lastPlayedAt: string | null, archivePresent: boolean, 
/**
 * On the `gfimg://` scheme, since an `<img>` cannot present our session.
 */
coverUrl: string | null, headerUrl: string | null, screenshotUrls: Array<string>, 
/**
 * Third-party links, passed through untouched.
 */
videoUrls: Array<string>, };
