// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of a games folder's two subfolders.
 */
export type LibraryFolder = "downloads" | "installations";
