// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `LibraryDto`.
 */
export type Library = { id: number, name: string, gameIds: Array<number>, };
