// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the stored login is, which decides whether it can outlive the server's session.
 */
export type LoginKind = "device-token" | "session";
