// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginPoll = { signedIn: boolean, windowOpen: boolean, 
/**
 * Cookies exist but do not authenticate yet, usually a proxy still in the way.
 */
detail: string | null, };
