// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of the sign-in window, forwarded to the wizard so it can show what is happening.
 */
export type LoginProgress = { host: string, 
/**
 * True once the window is back on the Gameyfin origin.
 */
onServer: boolean, };
