// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A small fixed set, so a user can turn detail up for a bug report without tracing syntax.
 */
export type LogLevel = "error" | "warn" | "info" | "debug" | "trace";
