// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The downloaded database of where games keep their saves. Separate from the helper's
 * version: it changes far more often, and an unrecognised game is usually waiting for it.
 */
export type ManifestInfo = { 
/**
 * When it was last written, RFC 3339.
 */
updatedAt: string | null, bytes: number, };
