// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrationSummary = { 
/**
 * Games the source held anything for.
 */
games: number, copied: number, 
/**
 * Already at the destination, byte for byte.
 */
skipped: number, failed: number, bytes: number, problems: Array<string>, };
