// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of event a notification reports, which decides the setting that gates it.
 */
export type NotificationCategory = "transfer" | "action" | "failure" | "update";
