// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveVersion } from "./SaveVersion";

/**
 * A stored version offered on a first start, and whether it restores on this PC.
 */
export type OfferedSave = { version: SaveVersion, restorable: boolean, };
