// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrefixEntry = { gameId: number, title: string | null, path: string, bytes: number, };
