// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Wine tool that can be run against one prefix.
 */
export type PrefixTool = "winecfg" | "explorer" | "regedit";
