// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtonFamily } from "./ProtonFamily";

export type ProtonRelease = { family: ProtonFamily, tag: string, asset: string, url: string, 
/**
 * The sibling `.sha512sum`. `None` when a release omits it, which is logged rather
 * than silently accepted.
 */
sumsUrl: string | null, sizeBytes: number, };
