// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledProton } from "./InstalledProton";
import type { ProtonRelease } from "./ProtonRelease";

export type ProtonStatus = { 
/**
 * Gameyfin's builds, then Steam's.
 */
installed: Array<InstalledProton>, defaultBuild: string | null, 
/**
 * What a game without its own pin runs with.
 */
inUse: string | null, latestUmu: ProtonRelease | null, latestGe: ProtonRelease | null, umuTags: Array<string>, geTags: Array<string>, launcherVersion: string | null, launcherProblem: string | null, 
/**
 * Whether 32-bit programs can run in the container at all.
 */
supports32bit: boolean, };
