// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledProton } from "./InstalledProton";
import type { ProtonRelease } from "./ProtonRelease";

export type ProtonStatus = { 
/**
 * At most one build per family, newest first.
 */
installed: Array<InstalledProton>, latestUmu: ProtonRelease | null, latestGe: ProtonRelease | null, launcherProblem: string | null, supports32bit: boolean, 
/**
 * 32-bit OpenGL drivers, without which a 32-bit program that draws with OpenGL cannot open a window.
 */
supports32bitGraphics: boolean, 
/**
 * Whether what is missing are Flatpak extensions, which the app can install.
 */
missingI386Extension: boolean, };
