// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveSyncState } from "./SaveSyncState";

/**
 * What a restore did: "in sync" alone does not say the save was just put back, or where.
 */
export type RestoreReport = { state: SaveSyncState, files: number, 
/**
 * Where the files went, leaving out folders nested in another.
 */
folders: Array<string>, 
/**
 * When the restored version was saved, and on which device.
 */
savedAt: string | null, device: string | null, };
