// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavePlatform } from "./SavePlatform";
import type { SaveVersion } from "./SaveVersion";

/**
 * What the UI shows for one game.
 */
export type SaveSyncState = { "kind": "off" } | { "kind": "unsupported" } | { "kind": "disabled" } | { "kind": "unmatched", candidates: Array<string>, } | { "kind": "never-synced" } | { "kind": "nothing-to-back-up", 
/**
 * The title it searched under, which is what the user needs to judge whether the
 * game was matched to the wrong entry or simply has nothing saved yet.
 */
title: string, 
/**
 * Whether the helper's database had anything to say about that title at all.
 */
known: boolean, } | { "kind": "in-sync", lastSyncedAt: string | null, } | { "kind": "local-newer", localAt: string | null, } | { "kind": "remote-newer", remoteAt: string | null, device: string | null, } | { "kind": "conflict", localAt: string | null, remote: SaveVersion, } | { "kind": "platform-mismatch", local: SavePlatform, remote: SavePlatform, 
/**
 * Whether Ludusavi's Wine translation could bridge it, as opposed to needing a
 * hand-written mapping.
 */
crossOsAvailable: boolean, } | { "kind": "failed", message: string, };
