// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which games the Saves tab is asking about.
 */
export type SaveScope = "installed" | "with-saves" | "all";
