// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This game's hand-set paths, so the dialog opens on what is configured.
 */
export type SavePathSettings = { customPaths: Array<string>, redirects: Array<[string, string]>, crossOs: boolean, };
