// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The offer to download saves that already exist, made once before a first play.
 */
export type SavePullOffer = { gameId: number, title: string, remoteAt: string | null, device: string | null, sizeBytes: number, };
