// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveVersion = { 
/**
 * Opaque store-issued id: a database id on the server, a filename in a folder or WebDAV store.
 */
id: string, gameId: number, gameTitle: string | null, sizeBytes: number, contentHash: string, platform: string, installationId: string | null, deviceName: string | null, ludusaviTitle: string | null, locked: boolean, createdAt: string | null, };
