// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveFindMatch } from "./SaveFindMatch";

/**
 * Saves the helper found on this PC for one game.
 */
export type SaveFind = { 
/**
 * The title the save database knows it by, which is what a backup is filed under.
 */
ludusaviTitle: string, files: number, bytes: number, 
/**
 * Where the files are, so the user can look before deciding.
 */
folder: string | null, gameId: number | null, gameTitle: string | null, matched: SaveFindMatch, 
/**
 * Whether the store already holds something for the game this was matched to.
 */
alreadyBackedUp: boolean, };
