// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferedSave } from "./OfferedSave";

/**
 * The stored saves offered on the first start of a game on this PC, newest first.
 */
export type SavePullOffer = { gameId: number, title: string, versions: Array<OfferedSave>, 
/**
 * Whether this PC already has save files for the game, which a restore replaces.
 */
localSaves: boolean, 
/**
 * When those files last changed, shown beside the stored saves' dates.
 */
localAt: string | null, };
