// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a find was matched to a game in the library.
 */
export type SaveFindMatch = "recorded" | "title" | "none";
