// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledSaveTool } from "./InstalledSaveTool";
import type { ManifestInfo } from "./ManifestInfo";
import type { SaveToolRelease } from "./SaveToolRelease";

export type SaveToolStatus = { 
/**
 * None until the helper has run once and downloaded it.
 */
manifest: ManifestInfo | null, 
/**
 * A user-installed copy, if there is one. Absent means the bundled build is in use.
 */
installed: InstalledSaveTool | null, 
/**
 * The version shipped with the app, which is the fallback.
 */
bundled: string | null, latest: SaveToolRelease | null, 
/**
 * Recent versions, newest first, for choosing a specific one.
 */
available: Array<string>, };
