// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveSyncPhase } from "./SaveSyncPhase";
import type { SyncMoment } from "./SyncMoment";

/**
 * What the window around a launch or an exit is told.
 */
export type SaveSyncProgress = { gameId: number, title: string, moment: SyncMoment, phase: SaveSyncPhase, 
/**
 * False once stopping would leave the save half written, so the button can say so.
 */
skippable: boolean, };
