// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveSyncState } from "./SaveSyncState";

export type SaveSyncPhase = { "kind": "checking" } | { "kind": "downloading" } | { "kind": "restoring" } | { "kind": "scanning" } | { "kind": "uploading" } | { "kind": "done", state: SaveSyncState, } | { "kind": "skipped" } | { "kind": "kept-local" } | { "kind": "asking" } | { "kind": "restored", files: number, folders: Array<string>, savedAt: string | null, device: string | null, } | { "kind": "failed", message: string, };
