// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Folders worth offering to open or to browse for one game's saves.
 */
export type SaveLocations = { 
/**
 * Holds every game's staging directory and the packed archives beside them.
 */
savesRoot: string | null, 
/**
 * What the helper backs this game up into.
 */
staging: string | null, 
/**
 * The Windows-side home inside the prefix, where a Proton game keeps its saves.
 */
prefixHome: string | null, 
/**
 * The prefix's drive C, for a game that keeps saves beside itself instead.
 */
prefixDriveC: string | null, installDir: string | null, home: string | null, 
/**
 * Where the helper actually found files. Only filled when asked for: it runs a scan.
 */
detected: Array<string>, };
