// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveToolRelease = { version: string, asset: string, url: string, sizeBytes: number, 
/**
 * From GitHub's asset digest: catches a corrupted transfer, not a malicious publisher.
 */
sha256: string | null, };
