// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveSyncState } from "./SaveSyncState";

/**
 * What an automatic sync is doing right now.
 */
export type SaveSyncPhase = { "kind": "checking" } | { "kind": "downloading" } | { "kind": "restoring" } | { "kind": "scanning" } | { "kind": "uploading" } | { "kind": "done", state: SaveSyncState, } | { "kind": "skipped" } | { "kind": "nothing-to-do" } | { "kind": "failed", message: string, };
