// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavePlatform } from "./SavePlatform";
import type { SaveSyncState } from "./SaveSyncState";

export type SaveOverviewRow = { gameId: number, title: string, installed: boolean, state: SaveSyncState, versions: number, newestAt: string | null, newestDevice: string | null, 
/**
 * The newest version's size, which is what the user recognises a save by.
 */
sizeBytes: number, remotePlatform: SavePlatform | null, 
/**
 * Whether anything has ever identified this game, so a row can offer to look.
 */
identified: boolean, };
