// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerProbe = { 
/**
 * The normalised URL the client will use.
 */
url: string, 
/**
 * Whether the server answered as a Gameyfin instance.
 */
reachable: boolean, 
/**
 * True when the server already considers this client signed in.
 */
authenticated: boolean, 
/**
 * Present when the server is reachable but not usable.
 */
message: string | null, };
