// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallerMemoryLimit } from "./InstallerMemoryLimit";
import type { LogLevel } from "./LogLevel";
import type { SaveBackend } from "./SaveBackend";
import type { Theme } from "./Theme";

export type Settings = { 
/**
 * Without a trailing slash.
 */
serverUrl: string | null, 
/**
 * The default games folder, first of [`Self::library_roots`].
 */
libraryRoot: string | null, extraLibraryRoots: Array<string>, username: string | null, logLevel: LogLevel, 
/**
 * Zero is unlimited. Client-side, since Gameyfin has no server throttle.
 */
downloadLimitKib: number, 
/**
 * Repack installers size buffers from all the RAM they find, so they are capped.
 */
installerMemoryLimit: InstallerMemoryLimit, 
/**
 * `None` is the server's highest-priority provider.
 */
downloadProvider: string | null, notifyTransfers: boolean, 
/**
 * Separate so failures stay audible with the routine chatter off.
 */
notifyFailures: boolean, notifyUpdates: boolean, closeToTray: boolean, startMinimized: boolean, autoInstall: boolean, deleteArchiveAfterExtract: boolean, deleteDownloadAfterInstall: boolean, umuFixes: boolean, umuAutoUpdate: boolean, gamepadEnabled: boolean, 
/**
 * 0.0 to 1.0; a worn stick rests off-centre.
 */
gamepadDeadzone: number, couchModeAuto: boolean, checkForUpdates: boolean, 
/**
 * Case-insensitive substrings of file names never offered as the game.
 */
ignoredExecutables: Array<string>, theme: Theme, autostart: boolean, 
/**
 * Lets the server name the device a save came from.
 */
installationId: string | null, saveManifestAutoUpdate: boolean, 
/**
 * Falls back to the host name.
 */
deviceName: string | null, saveSyncEnabled: boolean, syncSavesOnLaunch: boolean, syncSavesOnExit: boolean, saveBackend: SaveBackend, saveFolder: string | null, webdavUrl: string | null, webdavUsername: string | null, 
/**
 * Folder and WebDAV retention; a Gameyfin server keeps its own.
 */
saveMaxVersions: number, };
