// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupRole } from "./SetupRole";

/**
 * A setup program that came with a game, as the chooser offers it.
 */
export type SetupProgram = { 
/**
 * Relative to the unpacked download, or to the installed game's folder.
 */
path: string, role: SetupRole, 
/**
 * A patch the game installer already includes.
 */
superseded: boolean, installed: boolean, 
/**
 * Has silent switches, so it installs without asking anything. Not checked for unmatched ones.
 */
silent: boolean, 
/**
 * What an automatic install would run now.
 */
recommended: boolean, 
/**
 * Recognised by name as a setup, patch or DLC. The rest is every other program in the download.
 */
matched: boolean, };
