// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which shortcuts exist for a game, so the UI can show them as toggles.
 */
export type ShortcutStatus = { desktop: boolean, menu: boolean, 
/**
 * Whether Steam is installed at all, which decides if that option is offered.
 */
steamAvailable: boolean, steam: boolean, };
