// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of a play session a sync belongs to.
 */
export type SyncMoment = "launch" | "exit";
