// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the app knows about per-title Proton fixes.
 */
export type UmuStatus = { 
/**
 * Zero means the database has never been fetched.
 */
entries: number, ageSeconds: number | null, enabled: boolean, 
/**
 * The id a given game would get, when one was asked about.
 */
resolved: string | null, };
