// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryFolder } from "./LibraryFolder";

export type UntrackedFolder = { path: string, name: string, folder: LibraryFolder, bytes: number, 
/**
 * The id in its name, for a game the server no longer has.
 */
gameId: number | null, };
