// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOutcome = { message: string, 
/**
 * True when the new version is on disk and only a restart stands between it and the user.
 */
restartNeeded: boolean, };
