// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";

export type UpdateStatus = { currentVersion: string, 
/**
 * The newest published release, or null when the check could not be made.
 */
latestVersion: string | null, 
/**
 * True only when the newest release is genuinely newer than what is running.
 */
available: boolean, channel: Channel, canInstall: boolean, releaseUrl: string, 
/**
 * The release notes, trimmed to something a panel can show.
 */
notes: string | null, error: string | null, };
