// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProgress = { 
/**
 * The step being done, since not every format can count what it is doing.
 */
phase: string, receivedBytes: number, 
/**
 * Zero until the download knows how big it is.
 */
totalBytes: number, 
/**
 * For formats that report a percentage of their own rather than byte counts.
 */
percent: number | null, };
