// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the driver reports, or nothing at all when there is no usable Vulkan.
 */
export type VulkanSupport = { 
/**
 * Highest `apiVersion` across the physical devices, as major and minor.
 */
apiVersion: [number, number] | null, 
/**
 * The device that reported it, for the settings screen.
 */
device: string | null, };
