// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WineVariant } from "./WineVariant";

export type WineRelease = { version: string, variant: WineVariant, asset: string, url: string, sizeBytes: number, 
/**
 * From the release's `sha256sums.txt`. `None` when that file is absent, which is
 * reported rather than silently accepted.
 */
sha256: string | null, };
