// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledWine } from "./InstalledWine";
import type { WineChannel } from "./WineChannel";
import type { WineRelease } from "./WineRelease";

/**
 * Everything the settings screen needs to describe the Wine situation.
 */
export type WineStatus = { installed: InstalledWine | null, installedChannel: WineChannel | null, 
/**
 * Newest on the installed build's channel, stable when nothing is installed. `None`
 * when the feed could not be reached, which the UI must not read as up to date.
 */
latest: WineRelease | null, 
/**
 * Versions offering this variant, newest first.
 */
stable: Array<string>, development: Array<string>, };
