// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wine's release line, read from the version number itself.
 */
export type WineChannel = "stable" | "development";
